-- ═══════════════════════════════════════════════════════════════════════
-- Security lockdown, data integrity constraints, and the seat-reservation
-- machinery that makes overselling impossible.
--
-- This migration is hand-written and must NOT be regenerated by Prisma.
-- ═══════════════════════════════════════════════════════════════════════


-- ───────────────────────────────────────────────────────────────────────
-- 1. Link profiles to Supabase auth
--
-- Prisma can't own this FK: auth.users belongs to Supabase and must never
-- appear in our datamodel, or migrations would try to manage it.
-- ───────────────────────────────────────────────────────────────────────

ALTER TABLE "profiles"
  ADD CONSTRAINT "profiles_id_fkey"
  FOREIGN KEY ("id") REFERENCES auth.users(id) ON DELETE CASCADE;

-- Provision a profile row whenever someone signs up. Without this, a user
-- can authenticate but has no application identity, and every booking
-- insert fails on the FK.
CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, phone, created_at, updated_at)
  VALUES (
    NEW.id,
    NEW.email,
    NULLIF(NEW.raw_user_meta_data->>'full_name', ''),
    NULLIF(NEW.phone, ''),
    now(),
    now()
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_auth_user();


-- ───────────────────────────────────────────────────────────────────────
-- 2. Shut the public API off
--
-- Supabase auto-exposes every table in `public` through PostgREST using the
-- anon key — which ships in the browser bundle. Without RLS, anyone who
-- views source could read the entire bookings table, customer phone numbers
-- included.
--
-- Enabling RLS with ZERO policies makes those roles see nothing. Prisma
-- connects as the table owner and is unaffected (we deliberately do NOT use
-- FORCE ROW LEVEL SECURITY, which would also block the owner).
--
-- Authorization for real requests is enforced in server code, because
-- Prisma bypasses RLS by design.
-- ───────────────────────────────────────────────────────────────────────

ALTER TABLE "profiles"            ENABLE ROW LEVEL SECURITY;
ALTER TABLE "trips"               ENABLE ROW LEVEL SECURITY;
ALTER TABLE "trip_pricing_tiers"  ENABLE ROW LEVEL SECURITY;
ALTER TABLE "seat_holds"          ENABLE ROW LEVEL SECURITY;
ALTER TABLE "bookings"            ENABLE ROW LEVEL SECURITY;
ALTER TABLE "booking_travellers"  ENABLE ROW LEVEL SECURITY;
ALTER TABLE "booking_instalments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "payments"            ENABLE ROW LEVEL SECURITY;
ALTER TABLE "razorpay_events"     ENABLE ROW LEVEL SECURITY;
ALTER TABLE "reviews"             ENABLE ROW LEVEL SECURITY;
ALTER TABLE "enquiries"           ENABLE ROW LEVEL SECURITY;
ALTER TABLE "email_log"           ENABLE ROW LEVEL SECURITY;
ALTER TABLE "audit_log"           ENABLE ROW LEVEL SECURITY;
ALTER TABLE "site_settings"       ENABLE ROW LEVEL SECURITY;

-- Belt and braces: even with RLS on, don't hand these roles table grants.
REVOKE ALL ON ALL TABLES    IN SCHEMA public FROM anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM anon, authenticated;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  REVOKE ALL ON TABLES FROM anon, authenticated;


-- ───────────────────────────────────────────────────────────────────────
-- 3. Integrity constraints
--
-- These are the invariants that must hold no matter which code path writes.
-- Application bugs are inevitable; silent data corruption doesn't have to be.
-- ───────────────────────────────────────────────────────────────────────

ALTER TABLE "trips"
  ADD CONSTRAINT trips_total_seats_positive     CHECK ("total_seats" > 0),
  ADD CONSTRAINT trips_seats_booked_nonneg      CHECK ("seats_booked" >= 0),
  ADD CONSTRAINT trips_no_oversell              CHECK ("seats_booked" <= "total_seats"),
  ADD CONSTRAINT trips_price_nonneg             CHECK ("price_paise" >= 0),
  ADD CONSTRAINT trips_compare_price_nonneg     CHECK ("compare_price_paise" IS NULL OR "compare_price_paise" >= 0),
  ADD CONSTRAINT trips_advance_within_price     CHECK ("advance_paise" IS NULL OR ("advance_paise" >= 0 AND "advance_paise" <= "price_paise")),
  ADD CONSTRAINT trips_gst_range                CHECK ("gst_percent" BETWEEN 0 AND 100),
  ADD CONSTRAINT trips_instalments_range        CHECK ("instalment_count" BETWEEN 0 AND 6),
  ADD CONSTRAINT trips_min_participants_valid   CHECK ("min_participants" >= 1 AND "min_participants" <= "total_seats"),
  ADD CONSTRAINT trips_dates_ordered            CHECK ("end_date" >= "start_date");

ALTER TABLE "trip_pricing_tiers"
  ADD CONSTRAINT tiers_price_nonneg CHECK ("price_paise" >= 0);

ALTER TABLE "seat_holds"
  ADD CONSTRAINT holds_seats_positive CHECK ("seats" >= 1);

ALTER TABLE "bookings"
  ADD CONSTRAINT bookings_seats_positive   CHECK ("seats" >= 1),
  ADD CONSTRAINT bookings_amounts_nonneg   CHECK (
    "unit_price_paise" >= 0 AND "subtotal_paise" >= 0 AND
    "gst_paise" >= 0 AND "total_paise" >= 0 AND
    "amount_paid_paise" >= 0 AND "refunded_paise" >= 0
  ),
  ADD CONSTRAINT bookings_refund_within_paid CHECK ("refunded_paise" <= "amount_paid_paise");

ALTER TABLE "payments"
  ADD CONSTRAINT payments_amount_positive CHECK ("amount_paise" > 0);

ALTER TABLE "reviews"
  ADD CONSTRAINT reviews_rating_range CHECK ("rating" BETWEEN 1 AND 5);

-- Only live holds matter to availability; index just those.
CREATE INDEX seat_holds_live_idx
  ON "seat_holds" ("trip_id")
  WHERE "released_at" IS NULL AND "booking_id" IS NULL;


-- ───────────────────────────────────────────────────────────────────────
-- 4. reserve_seats() — the oversell guard
--
-- The naive approach (SELECT seats_booked, compare, INSERT) is broken:
-- five people racing for the last two seats all read "2 available" and all
-- succeed. FOR UPDATE on the trip row serialises them, so the check and the
-- write are atomic.
--
-- Returns the hold id. Raises with hint 'INSUFFICIENT_SEATS' when full.
-- ───────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.reserve_seats(
  p_trip_id      uuid,
  p_profile_id   uuid,
  p_seats        int,
  p_hold_minutes int DEFAULT 15
)
RETURNS uuid
LANGUAGE plpgsql
AS $$
DECLARE
  v_total      int;
  v_booked     int;
  v_held       int;
  v_available  int;
  v_status     "TripStatus";
  v_hold_id    uuid;
BEGIN
  IF p_seats < 1 THEN
    RAISE EXCEPTION 'seats must be at least 1' USING ERRCODE = '22023';
  END IF;

  -- Serialisation point. Everything below is safe because of this lock.
  SELECT "total_seats", "seats_booked", "status"
    INTO v_total, v_booked, v_status
  FROM "trips"
  WHERE "id" = p_trip_id AND "deleted_at" IS NULL
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'trip not found' USING ERRCODE = 'P0002', HINT = 'TRIP_NOT_FOUND';
  END IF;

  IF v_status <> 'PUBLISHED' THEN
    RAISE EXCEPTION 'trip is not open for booking' USING ERRCODE = 'P0001', HINT = 'TRIP_NOT_PUBLISHED';
  END IF;

  -- Live holds: not released, not converted, not expired.
  SELECT COALESCE(SUM("seats"), 0) INTO v_held
  FROM "seat_holds"
  WHERE "trip_id" = p_trip_id
    AND "released_at" IS NULL
    AND "booking_id" IS NULL
    AND "expires_at" > now();

  v_available := v_total - v_booked - v_held;

  IF p_seats > v_available THEN
    RAISE EXCEPTION 'only % seat(s) available', GREATEST(v_available, 0)
      USING ERRCODE = 'P0001', HINT = 'INSUFFICIENT_SEATS';
  END IF;

  INSERT INTO "seat_holds" ("id", "trip_id", "profile_id", "seats", "expires_at", "created_at")
  VALUES (gen_random_uuid(), p_trip_id, p_profile_id, p_seats,
          now() + make_interval(mins => p_hold_minutes), now())
  RETURNING "id" INTO v_hold_id;

  RETURN v_hold_id;
END;
$$;


-- ───────────────────────────────────────────────────────────────────────
-- 5. confirm_seat_hold() — hold becomes a real seat
--
-- Handles the case that WILL happen in production: payment succeeds after
-- the hold expired. If capacity still exists we honour it (the customer
-- paid; do not punish them for a slow webhook). If the trip filled in the
-- meantime we raise HOLD_EXPIRED_TRIP_FULL so the caller can refund and
-- surface it to an admin rather than silently overselling.
-- ───────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.confirm_seat_hold(
  p_hold_id    uuid,
  p_booking_id uuid
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
  v_trip_id   uuid;
  v_seats     int;
  v_expired   boolean;
  v_total     int;
  v_booked    int;
BEGIN
  SELECT "trip_id", "seats", ("expires_at" <= now())
    INTO v_trip_id, v_seats, v_expired
  FROM "seat_holds"
  WHERE "id" = p_hold_id
    AND "released_at" IS NULL
    AND "booking_id" IS NULL
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'hold not found or already consumed'
      USING ERRCODE = 'P0002', HINT = 'HOLD_UNAVAILABLE';
  END IF;

  SELECT "total_seats", "seats_booked" INTO v_total, v_booked
  FROM "trips" WHERE "id" = v_trip_id FOR UPDATE;

  -- An expired hold no longer reserves anything, so re-check against real
  -- capacity before honouring it.
  IF v_expired AND (v_booked + v_seats) > v_total THEN
    RAISE EXCEPTION 'hold expired and trip is now full'
      USING ERRCODE = 'P0001', HINT = 'HOLD_EXPIRED_TRIP_FULL';
  END IF;

  IF (v_booked + v_seats) > v_total THEN
    RAISE EXCEPTION 'trip is full' USING ERRCODE = 'P0001', HINT = 'INSUFFICIENT_SEATS';
  END IF;

  UPDATE "trips"
     SET "seats_booked" = "seats_booked" + v_seats,
         "updated_at"   = now()
   WHERE "id" = v_trip_id;

  UPDATE "seat_holds"
     SET "booking_id" = p_booking_id
   WHERE "id" = p_hold_id;
END;
$$;


-- ───────────────────────────────────────────────────────────────────────
-- 6. release_seats() — cancellations and refunds give the seat back
-- ───────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.release_seats(
  p_trip_id uuid,
  p_seats   int
)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  UPDATE "trips"
     SET "seats_booked" = GREATEST("seats_booked" - p_seats, 0),
         "updated_at"   = now()
   WHERE "id" = p_trip_id;
END;
$$;


-- ───────────────────────────────────────────────────────────────────────
-- 7. release_expired_holds() — the reaper
--
-- Holds expire by TIMESTAMP, not by this job. Availability already ignores
-- expired rows, so if the reaper stops running nothing oversells and no
-- seat is lost — the rows just accumulate. Call from a scheduled route.
-- ───────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.release_expired_holds()
RETURNS int
LANGUAGE plpgsql
AS $$
DECLARE
  v_count int;
BEGIN
  UPDATE "seat_holds"
     SET "released_at" = now()
   WHERE "released_at" IS NULL
     AND "booking_id"  IS NULL
     AND "expires_at" <= now();

  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$;


-- ───────────────────────────────────────────────────────────────────────
-- 8. Booking references
--
-- Sequence-backed so two simultaneous bookings can never collide, which a
-- COUNT(*)+1 scheme would.  e.g. DOT-2026-0142
-- ───────────────────────────────────────────────────────────────────────

CREATE SEQUENCE IF NOT EXISTS booking_reference_seq START 100;

CREATE OR REPLACE FUNCTION public.next_booking_reference()
RETURNS text
LANGUAGE sql
AS $$
  SELECT 'DOT-' || to_char(now() AT TIME ZONE 'Asia/Kolkata', 'YYYY') || '-'
         || lpad(nextval('booking_reference_seq')::text, 4, '0');
$$;
