"use server";

import { redirect } from "next/navigation";
import { z } from "zod";

import { resolveDestination } from "@/lib/auth";
import { parseDateFilter } from "@/lib/dates";
import { sendEmail } from "@/lib/email/send";
import { verificationEmail } from "@/lib/email/templates";
import { prisma } from "@/lib/prisma";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";
import { siteUrl } from "@/lib/siteUrl";

export type SignupState = {
  status: "idle" | "sent" | "error";
  email: string;
  error?: string;
  /** Per-field messages, keyed by input name, so each error sits by its input. */
  fieldErrors?: Record<string, string>;
  /** Echoed back so a rejected form doesn't lose everything already typed. */
  values?: Record<string, string>;
};

const MIN_AGE = 18;

const schema = z.object({
  fullName: z.string().trim().min(2, "Tell us your name").max(120),
  email: z.string().trim().toLowerCase().email("That doesn't look like an email address").max(160),
  phone: z
    .string()
    .trim()
    .min(1, "Phone number is required")
    .refine((v) => {
      const digits = v.replace(/\D/g, "");
      return digits.length >= 10 && digits.length <= 15;
    }, "Enter a valid phone number"),
  state: z.string().trim().min(1, "Choose your state"),
  city: z.string().trim().min(2, "Which city?").max(80),
  dateOfBirth: z
    .string()
    .trim()
    .min(1, "Date of birth is required")
    // Rejects impossible dates outright rather than letting Date roll
    // 2026-02-31 forward into March.
    .refine((v) => parseDateFilter(v) !== null, "Enter a valid date")
    // Checked before the age rule, so a date in the future says so instead of
    // reporting a negative age as "you must be 18 or older".
    .refine((v) => {
      const d = parseDateFilter(v);
      return !d || d <= new Date();
    }, "Date of birth can't be in the future")
    // Trips are 18+, and taking a booking from a minor is a problem nobody
    // wants to discover at the airport.
    .refine((v) => ageOn(new Date(v)) >= MIN_AGE, `You must be ${MIN_AGE} or older to book`)
    .refine((v) => ageOn(new Date(v)) < 120, "Check that date"),
  gender: z.enum(["MALE", "FEMALE"], { message: "Select one" }),
  password: z.string().min(8, "Use at least 8 characters").max(200),
});

function ageOn(dob: Date) {
  const now = new Date();
  let age = now.getFullYear() - dob.getFullYear();
  const monthDiff = now.getMonth() - dob.getMonth();
  if (monthDiff < 0 || (monthDiff === 0 && now.getDate() < dob.getDate())) age -= 1;
  return age;
}

/**
 * Creates an account and emails a confirmation link.
 *
 * Supabase Auth owns the credentials; the `on_auth_user_created` trigger
 * mirrors the row into `profiles`, picking up full_name from the metadata
 * passed here. Verification state is never duplicated — it lives only in
 * auth.users.email_confirmed_at.
 *
 * The link is generated by Supabase but sent by us through Resend, rather
 * than letting Supabase mail it. Supabase's built-in mailer is rate limited
 * to a handful of messages an hour and is explicitly not for production, and
 * doing it this way keeps every template the team sends in one place.
 */
export async function signUp(_prev: SignupState, formData: FormData): Promise<SignupState> {
  const raw = {
    fullName: String(formData.get("fullName") ?? ""),
    email: String(formData.get("email") ?? ""),
    phone: String(formData.get("phone") ?? ""),
    state: String(formData.get("state") ?? ""),
    city: String(formData.get("city") ?? ""),
    dateOfBirth: String(formData.get("dateOfBirth") ?? ""),
    gender: String(formData.get("gender") ?? ""),
    password: String(formData.get("password") ?? ""),
  };

  const parsed = schema.safeParse(raw);

  if (!parsed.success) {
    // Every field reports its own problem. One message at the top for eight
    // inputs means reading the whole form to find which one it meant.
    const fieldErrors: Record<string, string> = {};
    for (const issue of parsed.error.issues) {
      const key = String(issue.path[0] ?? "");
      if (key && !fieldErrors[key]) fieldErrors[key] = issue.message;
    }

    return {
      status: "error",
      email: raw.email,
      fieldErrors,
      // The password is deliberately not echoed back.
      values: { ...raw, password: "" },
    };
  }

  const { fullName, email, phone, state, city, dateOfBirth, gender, password } = parsed.data;
  const nextPath = sanitiseNext(String(formData.get("next") ?? ""));
  const admin = createAdminClient();

  // One call creates the unverified user AND mints the confirmation token.
  // The account exists but email_confirmed_at stays null until they click
  // the link, so an address nobody owns can't be used to book.
  //
  // full_name rides along in the metadata, which is what the
  // handle_new_auth_user trigger reads to populate the profile row.
  const { data, error } = await admin.auth.admin.generateLink({
    type: "signup",
    email,
    password,
    options: { data: { full_name: fullName, phone } },
  });

  if (error || !data.properties?.hashed_token) {
    if (error && /already|registered|exists/i.test(error.message)) {
      // The address may belong to an account the team created when they took
      // a booking over WhatsApp. That person has never signed in and never
      // set a password, so let this signup CLAIM it — otherwise they'd be
      // permanently locked out of a booking that is genuinely theirs.
      const claimed = await claimPreCreatedAccount({
        email, password, fullName, phone, state, city, dateOfBirth, gender, nextPath,
      });
      if (claimed) return { status: "sent", email };

      // Otherwise it's a real, verified account. Never confirm or deny that —
      // it would turn the signup form into a way to enumerate the customer
      // list — so report exactly what a genuine new signup reports.
      return { status: "sent", email };
    }
    console.error("[signup] generateLink failed", error?.message);
    return {
      status: "error",
      email,
      error: "We couldn't create that account. Try again.",
      values: { ...raw, password: "" },
    };
  }

  // The trigger populates id, email and full_name on insert; the rest of the
  // profile is written here because Supabase has no notion of these fields.
  if (data.user?.id) {
    await prisma.profile
      .update({
        where: { id: data.user.id },
        data: {
          fullName,
          phone,
          state,
          city,
          gender,
          // Date only, pinned to UTC midnight — a local-midnight Date would
          // shift a birthday across the date line for anyone east of UTC.
          dateOfBirth: new Date(`${dateOfBirth}T00:00:00.000Z`),
        },
      })
      .catch((e) => console.error("[signup] profile update failed", e));
  }

  const sent = await deliver({
    email,
    fullName,
    nextPath,
    hashedToken: data.properties.hashed_token,
    code: data.properties.email_otp,
  });

  if (!sent) {
    return {
      status: "error",
      email,
      error:
        "Your account was created, but we couldn't send the confirmation email. Sign in and we'll try again.",
      values: { ...raw, password: "" },
    };
  }

  return { status: "sent", email };
}

/** Re-sends the confirmation link for an address that hasn't confirmed yet. */
export async function resendVerification(
  _prev: SignupState,
  formData: FormData,
): Promise<SignupState> {
  const email = String(formData.get("email") ?? "").trim().toLowerCase();
  const nextPath = sanitiseNext(String(formData.get("next") ?? ""));

  if (!email) return { status: "error", email, error: "Enter your email address." };

  const profile = await prisma.profile.findUnique({
    where: { email },
    select: { fullName: true },
  });

  const admin = createAdminClient();
  // The account already exists by this point, so a fresh signup link can't
  // be minted — a magic link confirms the address just the same, and signs
  // them in when they follow it.
  const { data, error } = await admin.auth.admin.generateLink({ type: "magiclink", email });

  if (!error && data.properties?.hashed_token) {
    await deliver({
      email,
      fullName: profile?.fullName ?? null,
      nextPath,
      hashedToken: data.properties.hashed_token,
      code: data.properties.email_otp,
    });
  } else if (error) {
    console.error("[signup] resend generateLink failed", error.message);
  }

  // Always reports success: whether an address is registered is not
  // something an unauthenticated form should reveal.
  return { status: "sent", email };
}

/**
 * Lets a real person take ownership of an account the team pre-created.
 *
 * When an admin records a booking for someone who has never used the site,
 * an auth user is created so the booking has an owner. That account has no
 * password and has never been verified. If the same person later signs up,
 * refusing them would strand their booking behind an address they can't get
 * into — so their signup sets the password and details, and the emailed code
 * proves the address is theirs before they're let in.
 *
 * Only ever claims an UNVERIFIED account. A confirmed account belongs to
 * someone who has already proved that address, and overwriting its password
 * from an unauthenticated form would be account takeover.
 *
 * Returns false when the account isn't claimable, so the caller can fall
 * back to the neutral "check your email" response.
 */
async function claimPreCreatedAccount({
  email,
  password,
  fullName,
  phone,
  state,
  city,
  dateOfBirth,
  gender,
  nextPath,
}: {
  email: string;
  password: string;
  fullName: string;
  phone: string;
  state: string;
  city: string;
  dateOfBirth: string;
  gender: "MALE" | "FEMALE";
  nextPath: string;
}) {
  const admin = createAdminClient();

  const [row] = await prisma.$queryRaw<{ id: string; confirmed: boolean }[]>`
    SELECT id, email_confirmed_at IS NOT NULL AS confirmed
    FROM auth.users WHERE email = ${email}`;

  if (!row || row.confirmed) return false;

  const { error } = await admin.auth.admin.updateUserById(row.id, {
    password,
    user_metadata: { full_name: fullName, phone },
  });
  if (error) {
    console.error("[signup] claim failed", error.message);
    return false;
  }

  await prisma.profile
    .update({
      where: { id: row.id },
      data: {
        fullName,
        phone,
        state,
        city,
        gender,
        dateOfBirth: new Date(`${dateOfBirth}T00:00:00.000Z`),
      },
    })
    .catch((e) => console.error("[signup] claim profile update failed", e));

  // A magic link, not a signup link: the account already exists, and
  // verifying one confirms the address just the same.
  const { data, error: linkError } = await admin.auth.admin.generateLink({
    type: "magiclink",
    email,
  });

  if (linkError || !data.properties?.hashed_token) {
    console.error("[signup] claim link failed", linkError?.message);
    return false;
  }

  return deliver({
    email,
    fullName,
    nextPath,
    hashedToken: data.properties.hashed_token,
    code: data.properties.email_otp,
  });
}

async function deliver({
  email,
  fullName,
  nextPath,
  hashedToken,
  code,
}: {
  email: string;
  fullName: string | null;
  nextPath: string;
  hashedToken: string;
  code: string;
}) {
  // Resolved from the running deployment rather than hardcoded, so a link
  // emailed from staging opens staging and one from production opens
  // production, with no env var to remember.
  const confirmUrl = new URL("/auth/confirm", siteUrl());
  confirmUrl.searchParams.set("token_hash", hashedToken);
  confirmUrl.searchParams.set("type", "email");
  if (nextPath) confirmUrl.searchParams.set("next", nextPath);

  const mail = verificationEmail({ name: fullName, code, confirmUrl: confirmUrl.toString() });

  const result = await sendEmail({
    to: email,
    subject: mail.subject,
    html: mail.html,
    text: mail.text,
    template: "signup_verification",
    // Scoped to this token, so a genuine re-send always goes out while a
    // double-submitted form doesn't put two copies in the same inbox.
    dedupeKey: `verify:${hashedToken}`,
  });

  return result.ok;
}

export type VerifyState = {
  status: "idle" | "error";
  error?: string;
};

/**
 * Checks the emailed code and signs them in, without leaving the page.
 *
 * verifyOtp does both jobs at once — it marks the address confirmed and
 * issues the session — so there's no separate sign-in step afterwards.
 *
 * `type: "email"` rather than "signup" on purpose: it accepts codes minted
 * by both the signup and the resend paths, so this one action covers a first
 * attempt and a re-send without having to track which produced the code.
 */
export async function verifySignupOtp(
  _prev: VerifyState,
  formData: FormData,
): Promise<VerifyState> {
  const email = String(formData.get("email") ?? "").trim().toLowerCase();
  // People paste codes with spaces in them.
  const token = String(formData.get("token") ?? "").replace(/\D/g, "");
  const nextPath = sanitiseNext(String(formData.get("next") ?? ""));

  if (!email) return { status: "error", error: "Start again — we lost track of your email." };

  // Supabase's code length is a project setting, so don't hard-code it;
  // check a sane range instead or a valid code gets rejected before it's
  // ever sent for verification.
  if (token.length < 6 || token.length > 10) {
    return { status: "error", error: "Enter the code from your email." };
  }

  const supabase = await createClient();
  const { data, error } = await supabase.auth.verifyOtp({ email, token, type: "email" });

  if (error || !data.user) {
    return { status: "error", error: "That code isn't right, or it's expired. Try again." };
  }

  const profile = await prisma.profile.findUnique({
    where: { id: data.user.id },
    select: { role: true },
  });

  // Redirect from the server, not by handing a destination back to the
  // client. A completed server action re-renders the current route, and
  // /signup turns signed-in visitors away to /account — which beat the
  // client-side navigation every time and swallowed the real destination.
  //
  // redirect() throws to unwind, so nothing below it runs.
  redirect(resolveDestination(profile?.role ?? "CUSTOMER", nextPath));
}

/** Same-origin paths only — an open redirect here would be a phishing gift. */
function sanitiseNext(next: string) {
  return next.startsWith("/") && !next.startsWith("//") ? next : "";
}
