"use server";

import { redirect } from "next/navigation";
import { z } from "zod";

import { resolveDestination } from "@/lib/auth";
import { parseDateFilter } from "@/lib/dates";
import { sendEmail } from "@/emails";
import { verificationEmail } from "@/emails";
import { prisma } from "@/lib/prisma";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";
import { isValidPhone, toNationalDigits } from "@/lib/phone";

export type SignupState = {
  status: "idle" | "sent" | "error";
  email: string;
  error?: string;
  /** Per-field messages, keyed by input name, so each error sits by its input. */
  fieldErrors?: Record<string, string>;
  /** Echoed back so a rejected form doesn't lose everything already typed. */
  values?: Record<string, string>;
  /** Renders a "sign in instead" link beside the error. */
  existingAccount?: boolean;
};

const MIN_AGE = 18;

const schema = z.object({
  fullName: z.string().trim().min(2, "Tell us your name").max(120),
  email: z.string().trim().toLowerCase().email("That doesn't look like an email address").max(160),
  phone: z
    .string()
    .trim()
    .min(1, "Phone number is required")
    .refine(isValidPhone, "Enter a 10-digit mobile number")
    // Stored as ten national digits, so the same number can never arrive
    // as three different strings.
    .transform(toNationalDigits),
  state: z.string().trim().min(1, "Choose your state"),
  city: z.string().trim().min(2, "Which city?").max(80),
  dateOfBirth: z
    .string()
    .trim()
    .min(1, "Date of birth is required")
    // Rejects impossible dates outright rather than letting Date roll
    // 2026-02-31 forward into March.
    .refine((v) => parseDateFilter(v) !== null, "Enter a valid date")
    // Checked before the age rule, so a date in the future says so instead of
    // reporting a negative age as "you must be 18 or older".
    .refine((v) => {
      const d = parseDateFilter(v);
      return !d || d <= new Date();
    }, "Date of birth can't be in the future")
    // Trips are 18+, and taking a booking from a minor is a problem nobody
    // wants to discover at the airport.
    .refine((v) => ageOn(new Date(v)) >= MIN_AGE, `You must be ${MIN_AGE} or older to book`)
    .refine((v) => ageOn(new Date(v)) < 120, "Check that date"),
  gender: z.enum(["MALE", "FEMALE"], { message: "Select one" }),
  password: z.string().min(8, "Use at least 8 characters").max(200),
});

function ageOn(dob: Date) {
  const now = new Date();
  let age = now.getFullYear() - dob.getFullYear();
  const monthDiff = now.getMonth() - dob.getMonth();
  if (monthDiff < 0 || (monthDiff === 0 && now.getDate() < dob.getDate())) age -= 1;
  return age;
}

/**
 * Creates an account and emails a confirmation link.
 *
 * Supabase Auth owns the credentials; the `on_auth_user_created` trigger
 * mirrors the row into `profiles`, picking up full_name from the metadata
 * passed here. Verification state is never duplicated — it lives only in
 * auth.users.email_confirmed_at.
 *
 * The link is generated by Supabase but sent by us through Resend, rather
 * than letting Supabase mail it. Supabase's built-in mailer is rate limited
 * to a handful of messages an hour and is explicitly not for production, and
 * doing it this way keeps every template the team sends in one place.
 */
export async function signUp(_prev: SignupState, formData: FormData): Promise<SignupState> {
  const raw = {
    fullName: String(formData.get("fullName") ?? ""),
    email: String(formData.get("email") ?? ""),
    phone: String(formData.get("phone") ?? ""),
    state: String(formData.get("state") ?? ""),
    city: String(formData.get("city") ?? ""),
    dateOfBirth: String(formData.get("dateOfBirth") ?? ""),
    gender: String(formData.get("gender") ?? ""),
    password: String(formData.get("password") ?? ""),
  };

  const parsed = schema.safeParse(raw);

  if (!parsed.success) {
    // Every field reports its own problem. One message at the top for eight
    // inputs means reading the whole form to find which one it meant.
    const fieldErrors: Record<string, string> = {};
    for (const issue of parsed.error.issues) {
      const key = String(issue.path[0] ?? "");
      if (key && !fieldErrors[key]) fieldErrors[key] = issue.message;
    }

    return {
      status: "error",
      email: raw.email,
      fieldErrors,
      // The password is deliberately not echoed back.
      values: { ...raw, password: "" },
    };
  }

  const { fullName, email, phone, state, city, dateOfBirth, gender, password } = parsed.data;
  const nextPath = sanitiseNext(String(formData.get("next") ?? ""));
  const admin = createAdminClient();

  // One call creates the unverified user AND mints the confirmation token.
  // The account exists but email_confirmed_at stays null until they click
  // the link, so an address nobody owns can't be used to book.
  //
  // full_name rides along in the metadata, which is what the
  // handle_new_auth_user trigger reads to populate the profile row.
  const { data, error } = await admin.auth.admin.generateLink({
    type: "signup",
    email,
    password,
    options: { data: { full_name: fullName, phone } },
  });

  if (error || !data.properties?.hashed_token) {
    if (error && /already|registered|exists/i.test(error.message)) {
      // The address may belong to an account the team created when they took
      // a booking over WhatsApp. That person has never signed in and never
      // set a password, so let this signup CLAIM it — otherwise they'd be
      // permanently locked out of a booking that is genuinely theirs.
      const outcome = await claimPreCreatedAccount({
        email, password, fullName, phone, state, city, dateOfBirth, gender, nextPath,
      });

      if (outcome === "claimed") return { status: "sent", email };

      if (outcome === "verified") {
        // A real account that has already proved this address. We tell the
        // person so, rather than staging a fake "check your email", because
        // silently doing nothing is the single most confusing thing this form
        // can do — they wait for a code that is never coming.
        //
        // The cost is real and deliberate: this makes signup an oracle for
        // whether an address has an account here. Login and password reset
        // already behave the same way, so the information is not new, but it
        // is now available without any guesswork.
        return {
          status: "error",
          email,
          error: "An account already exists with this email address.",
          existingAccount: true,
          values: { ...raw, password: "" },
        };
      }

      // "failed" — the account exists but something went wrong claiming it.
      // Don't say "already exists": the password may have just been changed,
      // and sending them to log in with the old one would be a dead end.
      return {
        status: "error",
        email,
        error: "We couldn't finish setting up that account. Try again in a moment.",
        values: { ...raw, password: "" },
      };
    }
    console.error("[signup] generateLink failed", error?.message);
    return {
      status: "error",
      email,
      error: "We couldn't create that account. Try again.",
      values: { ...raw, password: "" },
    };
  }

  // The trigger populates id, email and full_name on insert; the rest of the
  // profile is written here because Supabase has no notion of these fields.
  if (data.user?.id) {
    await prisma.profile
      .update({
        where: { id: data.user.id },
        data: {
          fullName,
          phone,
          state,
          city,
          gender,
          // Date only, pinned to UTC midnight — a local-midnight Date would
          // shift a birthday across the date line for anyone east of UTC.
          dateOfBirth: new Date(`${dateOfBirth}T00:00:00.000Z`),
        },
      })
      .catch((e) => console.error("[signup] profile update failed", e));
  }

  const sent = await deliver({
    email,
    fullName,
    code: data.properties.email_otp,
    hashedToken: data.properties.hashed_token,
  });

  if (!sent) {
    return {
      status: "error",
      email,
      error:
        "Your account was created, but we couldn't send the confirmation email. Sign in and we'll try again.",
      values: { ...raw, password: "" },
    };
  }

  return { status: "sent", email };
}

/**
 * Answers whether an address already belongs to a usable account, so the
 * signup form can say so while someone is still filling it in rather than
 * after they've typed everything and pressed the button.
 *
 * Mirrors the rule in signUp() exactly: only a CONFIRMED account is a
 * conflict. An unconfirmed one was pre-created by the team for a booking
 * taken over WhatsApp, and signup is allowed to claim it — reporting that as
 * "taken" would block the very people it was created for.
 *
 * This is advisory. The form does not gate submission on it, because a
 * network blip must not stop someone signing up, and signUp() re-checks
 * server-side regardless.
 *
 * Worth being clear-eyed about: this is an endpoint that answers "does this
 * address have an account here?" to anyone who asks, quickly and repeatedly.
 * That follows from the decision to name the collision on this form at all —
 * but a form submission is slow and scriptable only clumsily, whereas this is
 * neither. If enumeration ever matters more than the UX, this is the thing to
 * put behind a rate limit.
 */
export async function checkEmailAvailability(email: string): Promise<{ taken: boolean }> {
  const clean = String(email ?? "").trim().toLowerCase();

  // Don't answer for anything that isn't a plausible address — no reason to
  // let the endpoint be probed with junk.
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(clean) || clean.length > 160) {
    return { taken: false };
  }

  try {
    const [row] = await prisma.$queryRaw<{ confirmed: boolean }[]>`
      SELECT email_confirmed_at IS NOT NULL AS confirmed
      FROM auth.users WHERE email = ${clean}`;

    return { taken: Boolean(row?.confirmed) };
  } catch (e) {
    // Never let a lookup failure present as "this address is taken".
    console.error("[signup] email availability check failed", e);
    return { taken: false };
  }
}

/** Re-sends the confirmation link for an address that hasn't confirmed yet. */
export async function resendVerification(
  _prev: SignupState,
  formData: FormData,
): Promise<SignupState> {
  const email = String(formData.get("email") ?? "").trim().toLowerCase();
  const nextPath = sanitiseNext(String(formData.get("next") ?? ""));

  if (!email) return { status: "error", email, error: "Enter your email address." };

  const profile = await prisma.profile.findUnique({
    where: { email },
    select: { fullName: true },
  });

  const admin = createAdminClient();
  // The account already exists by this point, so a fresh signup link can't
  // be minted — a magic link confirms the address just the same, and signs
  // them in when they follow it.
  const { data, error } = await admin.auth.admin.generateLink({ type: "magiclink", email });

  if (!error && data.properties?.hashed_token) {
    await deliver({
      email,
      fullName: profile?.fullName ?? null,
      code: data.properties.email_otp,
      hashedToken: data.properties.hashed_token,
    });
  } else if (error) {
    console.error("[signup] resend generateLink failed", error.message);
  }

  // Always reports success: whether an address is registered is not
  // something an unauthenticated form should reveal.
  return { status: "sent", email };
}

/**
 * Lets a real person take ownership of an account the team pre-created.
 *
 * When an admin records a booking for someone who has never used the site,
 * an auth user is created so the booking has an owner. That account has no
 * password and has never been verified. If the same person later signs up,
 * refusing them would strand their booking behind an address they can't get
 * into — so their signup sets the password and details, and the emailed code
 * proves the address is theirs before they're let in.
 *
 * Only ever claims an UNVERIFIED account. A confirmed account belongs to
 * someone who has already proved that address, and overwriting its password
 * from an unauthenticated form would be account takeover.
 *
 * Returns which of three things happened, because the caller has to say
 * something different for each:
 *
 *   "claimed"  — the account was unverified, is now theirs, code sent
 *   "verified" — a real account already owns this address; tell them to log in
 *   "failed"   — it exists but something broke; do NOT send them to log in,
 *                the password may have just changed underneath them
 */
type ClaimOutcome = "claimed" | "verified" | "failed";
async function claimPreCreatedAccount({
  email,
  password,
  fullName,
  phone,
  state,
  city,
  dateOfBirth,
  gender,
  nextPath,
}: {
  email: string;
  password: string;
  fullName: string;
  phone: string;
  state: string;
  city: string;
  dateOfBirth: string;
  gender: "MALE" | "FEMALE";
  nextPath: string;
}): Promise<ClaimOutcome> {
  const admin = createAdminClient();

  const [row] = await prisma.$queryRaw<{ id: string; confirmed: boolean }[]>`
    SELECT id, email_confirmed_at IS NOT NULL AS confirmed
    FROM auth.users WHERE email = ${email}`;

  // No row at all means generateLink rejected the address for some reason
  // other than "taken" — not something to send anyone to the login page over.
  if (!row) return "failed";

  // Confirmed: someone has already proved this address. Overwriting its
  // password from an unauthenticated form would be account takeover.
  if (row.confirmed) return "verified";

  const { error } = await admin.auth.admin.updateUserById(row.id, {
    password,
    user_metadata: { full_name: fullName, phone },
  });
  if (error) {
    console.error("[signup] claim failed", error.message);
    return "failed";
  }

  await prisma.profile
    .update({
      where: { id: row.id },
      data: {
        fullName,
        phone,
        state,
        city,
        gender,
        dateOfBirth: new Date(`${dateOfBirth}T00:00:00.000Z`),
      },
    })
    .catch((e) => console.error("[signup] claim profile update failed", e));

  // A magic link, not a signup link: the account already exists, and
  // verifying one confirms the address just the same.
  const { data, error: linkError } = await admin.auth.admin.generateLink({
    type: "magiclink",
    email,
  });

  if (linkError || !data.properties?.hashed_token) {
    console.error("[signup] claim link failed", linkError?.message);
    return "failed";
  }

  const sent = await deliver({
    email,
    fullName,
    code: data.properties.email_otp,
    hashedToken: data.properties.hashed_token,
  });

  // The password IS now theirs even if the mail bounced, so "failed" here
  // means "we couldn't get you the code", not "nothing happened".
  return sent ? "claimed" : "failed";
}

async function deliver({
  email,
  fullName,
  code,
  hashedToken,
}: {
  email: string;
  fullName: string | null;
  code: string;
  /**
   * Only used to key the dedupe. Kept rather than switching to `code`
   * because it is already a hash — the code itself is a live secret for an
   * hour, and email_log.dedupe_key is not the place to keep one.
   */
  hashedToken: string;
}) {
  // No link is built any more — verification is the code alone. See the note
  // on verificationEmail for why.
  const mail = verificationEmail({ name: fullName, code });

  const result = await sendEmail({
    to: email,
    subject: mail.subject,
    html: mail.html,
    text: mail.text,
    template: "signup_verification",
    // Scoped to this token, so a genuine re-send always goes out while a
    // double-submitted form doesn't put two copies in the same inbox.
    dedupeKey: `verify:${hashedToken}`,
  });

  return result.ok;
}

export type VerifyState = {
  status: "idle" | "error";
  error?: string;
};

/**
 * Checks the emailed code and signs them in, without leaving the page.
 *
 * verifyOtp does both jobs at once — it marks the address confirmed and
 * issues the session — so there's no separate sign-in step afterwards.
 *
 * `type: "email"` rather than "signup" on purpose: it accepts codes minted
 * by both the signup and the resend paths, so this one action covers a first
 * attempt and a re-send without having to track which produced the code.
 */
export async function verifySignupOtp(
  _prev: VerifyState,
  formData: FormData,
): Promise<VerifyState> {
  const email = String(formData.get("email") ?? "").trim().toLowerCase();
  // People paste codes with spaces in them.
  const token = String(formData.get("token") ?? "").replace(/\D/g, "");
  const nextPath = sanitiseNext(String(formData.get("next") ?? ""));

  if (!email) return { status: "error", error: "Start again — we lost track of your email." };

  // Supabase's code length is a project setting, so don't hard-code it;
  // check a sane range instead or a valid code gets rejected before it's
  // ever sent for verification.
  if (token.length < 6 || token.length > 10) {
    return { status: "error", error: "Enter the code from your email." };
  }

  const supabase = await createClient();
  const { data, error } = await supabase.auth.verifyOtp({ email, token, type: "email" });

  if (error || !data.user) {
    return { status: "error", error: "That code isn't right, or it's expired. Try again." };
  }

  const profile = await prisma.profile.findUnique({
    where: { id: data.user.id },
    select: { role: true },
  });

  // Redirect from the server, not by handing a destination back to the
  // client. A completed server action re-renders the current route, and
  // /signup turns signed-in visitors away to /account — which beat the
  // client-side navigation every time and swallowed the real destination.
  //
  // redirect() throws to unwind, so nothing below it runs.
  redirect(resolveDestination(profile?.role ?? "CUSTOMER", nextPath));
}

/** Same-origin paths only — an open redirect here would be a phishing gift. */
function sanitiseNext(next: string) {
  return next.startsWith("/") && !next.startsWith("//") ? next : "";
}
